import { type MouseEvent, useEffect, useState } from "react";
import { ArrowDownToLine, ArrowLeft, Check, CheckCheck, CheckSquare2, Info, MoreVertical, Search, Volume2, VolumeX } from "lucide-react";
import { Button } from "@codexsun/ui/components/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@codexsun/ui/components/dropdown-menu";
import { MessageActions } from "./messaging.message-actions";
import { downloadMessagingAttachment, fetchMessagingAttachment } from "./messaging.services";
import type { Conversation, Message } from "./messaging.types";

export function ConversationList({ actorEmail, conversations, loading, onSelect, selectedId }: { actorEmail: string; conversations: Conversation[]; loading: boolean; onSelect: (id: number) => void; selectedId: number | null }) {
  if (loading) return <p className="p-5 text-sm text-muted-foreground">Loading your conversations…</p>;
  if (!conversations.length) return <div className="flex flex-1 flex-col items-center justify-center gap-2 p-8 text-center"><Search className="size-7 text-muted-foreground" /><p className="text-sm font-medium">No chats found</p><p className="text-sm text-muted-foreground">Start a chat with a CRM user.</p></div>;
  return <ul className="flex-1 overflow-y-auto px-2 pb-4">{conversations.map((conversation) => { const title = conversationTitle(conversation, actorEmail); return <li key={conversation.id}><button aria-current={conversation.id === selectedId ? "page" : undefined} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition-colors ${conversation.id === selectedId ? "bg-primary/10" : "hover:bg-muted"}`} onClick={() => onSelect(conversation.id)} type="button"><Avatar label={title} /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{title}</span><span className={`block truncate text-sm ${conversation.unreadCount ? "font-medium text-foreground" : "text-muted-foreground"}`}>{conversation.lastMessage ? messagePreview(conversation.lastMessage) : conversation.type === "DIRECT" ? "Start a conversation" : `${conversation.members.length} participants`}</span></span><span className="flex w-14 shrink-0 flex-col items-end gap-1"><time className={`text-xs ${conversation.unreadCount ? "font-medium text-primary" : "text-muted-foreground"}`}>{formatListTime(conversation.updatedAt)}</time>{conversation.unreadCount ? <span className="grid min-w-5 place-items-center rounded-full bg-primary px-1.5 text-[11px] font-semibold leading-5 text-primary-foreground">{conversation.unreadCount > 99 ? "99+" : conversation.unreadCount}</span> : null}</span></button></li>; })}</ul>;
}
export function ThreadHeader({ actorEmail, conversation, onBack, onSearch, status }: { actorEmail: string; conversation: Conversation; onBack: () => void; onSearch: () => void; status: "connecting" | "open" | "closed" }) { const [muted, setMuted] = useState(false); const title = conversationTitle(conversation, actorEmail); return <header className="flex h-[64px] items-center gap-3 border-b bg-background px-3 md:px-4"><Button aria-label="Back to conversations" className="lg:hidden" onClick={onBack} size="icon" type="button" variant="ghost"><ArrowLeft className="size-5" /></Button><Avatar label={title} /><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold">{title}</h2><p className={`text-xs ${status === "open" ? "text-emerald-600" : "text-muted-foreground"}`}>{status === "open" ? "Online" : status === "connecting" ? "Connecting…" : "Offline"}</p></div><Button aria-label="Search messages" onClick={onSearch} size="icon" title="Search messages" type="button" variant="ghost"><Search className="size-5" /></Button><DropdownMenu><DropdownMenuTrigger asChild><Button aria-label="Chat options" size="icon" title="Chat options" type="button" variant="ghost"><MoreVertical className="size-5" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-56 rounded-xl p-1.5"><DropdownMenuItem onSelect={() => window.alert(`${title}\n${conversation.members.length} participant${conversation.members.length === 1 ? "" : "s"}`)}><Info className="mr-3 size-4" />Chat info</DropdownMenuItem><DropdownMenuItem onSelect={onSearch}><Search className="mr-3 size-4" />Search messages</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onSelect={() => setMuted(!muted)}>{muted ? <Volume2 className="mr-3 size-4" /> : <VolumeX className="mr-3 size-4" />}{muted ? "Unmute notifications" : "Mute notifications"}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></header>; }
export function MessageBubble({ message, mine, onReact }: { message: Message; mine: boolean; onReact: (emoji: string | null) => void }) {
  const [hidden, setHidden] = useState(false);
  if (hidden) return null;
  if (message.type === "SYSTEM") return <p className="mx-auto w-fit rounded-full bg-background/90 px-3 py-1 text-xs text-muted-foreground shadow-sm">{message.content}</p>;
  const attachment = messageAttachment(message);
  const openActions = (event: MouseEvent<HTMLDivElement>) => { event.preventDefault(); window.dispatchEvent(new CustomEvent("messaging:open-actions", { detail: message.id })); };
  return <div className={`group flex py-1.5 ${mine ? "justify-end" : "justify-start"}`}><div className={`relative min-w-[140px] max-w-[86%] rounded-2xl border px-3 pb-2 pt-2 text-sm shadow-[0_2px_5px_rgba(35,24,46,0.18)] md:max-w-[70%] ${mine ? "rounded-br-md border-[#D9C8E6] bg-[#F1E7F8] text-[#25182D]" : "rounded-bl-md border-[#E2E4E9] bg-white text-foreground"}`} onContextMenu={openActions}>{message.type === "TASK" ? <div className="mb-1 flex items-center gap-2 rounded-lg border border-primary/20 bg-primary/5 px-3 py-2"><CheckSquare2 className="size-4 text-primary" /><span className="font-medium">Task</span></div> : null}{attachment ? <Attachment attachment={attachment} /> : null}{deliveryLabel(message) ? <p className="mb-1 text-xs font-medium text-primary">Sent to {deliveryLabel(message)}</p> : null}<p className="whitespace-pre-wrap break-words pr-5 leading-relaxed">{highlightMentions(message.content)}</p><span className="flex items-center justify-end gap-1 pt-1 text-[11px] text-muted-foreground"><time>{formatMessageTime(message.createdAt)}</time>{mine ? message.status === "READ" ? <CheckCheck className="size-3.5 text-sky-600" /> : message.status === "DELIVERED" ? <CheckCheck className="size-3.5" /> : <Check className="size-3.5" /> : null}</span><MessageActions message={message} mine={mine} onHide={() => setHidden(true)} onReact={onReact} /></div></div>;
}
function Avatar({ label }: { label: string }) { const initials = label.split(/\s+/u).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); return <span aria-hidden="true" className="grid size-10 shrink-0 place-items-center rounded-full bg-primary/10 text-sm font-semibold text-primary">{initials || "?"}</span>; }
const indiaTimeZone = "Asia/Kolkata";
function formatListTime(value: string) { const date = new Date(value); const today = new Date(); return indiaDate(date) === indiaDate(today) ? formatMessageTime(value) : date.toLocaleDateString("en-IN", { day: "2-digit", month: "short", timeZone: indiaTimeZone }); }
function formatMessageTime(value: string) { return new Date(value).toLocaleTimeString("en-US", { hour: "2-digit", hour12: true, minute: "2-digit", timeZone: indiaTimeZone }); }
function indiaDate(value: Date) { return value.toLocaleDateString("en-CA", { timeZone: indiaTimeZone }); }
function messagePreview(message: Message) { const prefix = message.type === "VOICE" ? "Voice message" : message.type === "IMAGE" ? "Photo" : message.type === "FILE" ? "Attachment" : message.type === "TASK" ? "Task" : ""; return prefix ? `${prefix}${message.content ? ` · ${message.content}` : ""}` : message.content; }
type AttachmentData = { dataUrl: string; name: string; size: number; type: string };
function messageAttachment(message: Message): AttachmentData | null { const value = message.metadata.attachment; if (!value || typeof value !== "object") return null; const item = value as Record<string, unknown>; const url = typeof item.url === "string" ? item.url : item.dataUrl; return typeof url === "string" && typeof item.name === "string" ? { dataUrl: url, name: item.name, size: typeof item.size === "number" ? item.size : 0, type: typeof item.contentType === "string" ? item.contentType : typeof item.type === "string" ? item.type : "application/octet-stream" } : null; }
function Attachment({ attachment }: { attachment: AttachmentData }) { const source = useMediaSource(attachment.dataUrl); if (!source) return <span className="mb-2 flex items-center gap-2 rounded-xl bg-background/60 px-3 py-2 text-sm text-muted-foreground">Loading attachment…</span>; if (attachment.type.startsWith("image/")) return <a href={source} rel="noreferrer" target="_blank"><img alt={attachment.name} className="mb-2 max-h-72 w-full rounded-xl object-cover" src={source} /></a>; if (attachment.type.startsWith("audio/")) return <audio className="mb-2 max-w-full" controls src={source} />; return <button className="mb-2 flex w-full items-center gap-2 rounded-xl bg-background/60 px-3 py-2 font-medium" onClick={() => void downloadMessagingAttachment(attachment.dataUrl, attachment.name)} type="button"><ArrowDownToLine className="size-4" /><span className="min-w-0 flex-1 truncate text-left">{attachment.name}</span></button>; }
function useMediaSource(path: string) { const [source, setSource] = useState<string>(); useEffect(() => { let active = true; let objectUrl: string | undefined; void fetchMessagingAttachment(path).then((url) => { objectUrl = url; if (active) setSource(url); else URL.revokeObjectURL(url); }).catch(() => active && setSource(undefined)); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [path]); return source; }
function highlightMentions(content: string) { return content.split(/(@[^\s]+)/u).map((part, index) => part.startsWith("@") ? <span className="font-semibold text-primary" key={`${part}-${index}`}>{part}</span> : part); }
function deliveryLabel(message: Message) { const recipients = message.metadata.deliveryRecipients; return Array.isArray(recipients) ? recipients.filter((value): value is string => typeof value === "string").join(", ") : ""; }
export function conversationTitle(conversation: Conversation, actorEmail: string) { if (conversation.title) return conversation.title; const others = conversation.members.filter((member) => member.email !== actorEmail); return others.map((member) => member.userName).join(", ") || "Saved messages"; }
